#!/bin/bash

function git_cube_finish {
    IFS=$'\n'
    status=$(git status --porcelain -b 2>/dev/null || exit)  # Quit if this isn't a git repo

    dirty=false

    for line in $status; do
        xy=$(echo $line | cut -d ' ' -f 1)

        if [ "$xy" = "##" ]; then
            if [ -z "${line##*]}" ]; then
                dirty=true
                break
            fi
        elif [ "$xy" != "??" ]; then
            dirty=true
            break
        fi
    done

    if $dirty; then
        git status
        echo
        echo "Please tidy up after yourself!"
        echo

        if [ "$1" != "test" ]; then
            GIT_CUBE=1 exec bash
        fi
    fi
}

if [ "$BASH_SOURCE" = "$0" ]; then
    # We're being run directly - this is a test
    git_cube_finish "test"
else
    # We're being sourced
    if [ ${GIT_CUBE-0} -ne 1 ]; then
        trap git_cube_finish EXIT
    fi
fi
